// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Game$ReasonScripts from "../components/Game/game.bs.js";
import * as Home$ReasonScripts from "../components/Home/home.bs.js";
import * as ReactTransitionGroup$ReasonScripts from "../utils/ReactTransitionGroup.bs.js";

function routeToString(param) {
  if (param) {
    return "/game";
  } else {
    return "/";
  }
}

function urlToRoute(url) {
  var match = url[/* path */0];
  if (match && match[0] === "game" && !match[1]) {
    return /* Game */1;
  } else {
    return /* Home */0;
  }
}

function routeToTitle(route) {
  if (route) {
    return "Game";
  } else {
    return "Home";
  }
}

function routeToComponent(currentRoute) {
  var withCSSTransition = function (component, route) {
    return ReasonReact.element(/* Some */[route ? "Game" : "Home"], /* None */0, ReactTransitionGroup$ReasonScripts.CSSTransition[/* make */0](/* Some */[true], 900, "routeTransition", /* array */[component]));
  };
  if (currentRoute) {
    return withCSSTransition(ReasonReact.element(/* None */0, /* None */0, Game$ReasonScripts.make(/* array */[])), /* Game */1);
  } else {
    return withCSSTransition(ReasonReact.element(/* None */0, /* None */0, Home$ReasonScripts.make(/* array */[])), /* Home */0);
  }
}

export {
  routeToString ,
  urlToRoute ,
  routeToTitle ,
  routeToComponent ,
  
}
/* ReasonReact Not a pure module */
