// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Config$ReasonScripts from "../../route/Config.bs.js";
import * as ReactTransitionGroup$ReasonScripts from "../../utils/ReactTransitionGroup.bs.js";

((require('./app.css')));

var component = ReasonReact.statelessComponent("App");

function make(currentRoute, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "App"
                        }, React.createElement("main", undefined, ReasonReact.element(/* None */0, /* None */0, ReactTransitionGroup$ReasonScripts.TransitionGroup[/* make */0](/* array */[Config$ReasonScripts.routeToComponent(currentRoute)]))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  component ,
  make ,
  
}
/*  Not a pure module */
