// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as App$ReasonScripts from "./components/App/app.bs.js";
import * as Router$ReasonScripts from "./route/Router.bs.js";
import * as RegisterServiceWorker from "./registerServiceWorker";

((require('./index.css')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Router$ReasonScripts.WithRouter[/* make */1]((function (currentRoute) {
                return ReasonReact.element(/* None */0, /* None */0, App$ReasonScripts.make(currentRoute, /* array */[]));
              }))), "root");

RegisterServiceWorker.default();

export {
  
}
/*  Not a pure module */
