// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Caml_builtin_exceptions from "bs-platform/lib/es6/caml_builtin_exceptions.js";

var rowComponent = ReasonReact.statelessComponent("Skeleton");

function make(startTime, deathTime, time, lane, status, _) {
  return /* record */[
          /* debugName */rowComponent[/* debugName */0],
          /* reactClassInternal */rowComponent[/* reactClassInternal */1],
          /* handedOffState */rowComponent[/* handedOffState */2],
          /* willReceiveProps */rowComponent[/* willReceiveProps */3],
          /* didMount */rowComponent[/* didMount */4],
          /* didUpdate */rowComponent[/* didUpdate */5],
          /* willUnmount */rowComponent[/* willUnmount */6],
          /* willUpdate */rowComponent[/* willUpdate */7],
          /* shouldUpdate */rowComponent[/* shouldUpdate */8],
          /* render */(function () {
              var startPosition = time - startTime | 0;
              var timeString = [String((startPosition << 1)) + "px"];
              var switcher = lane - 1 | 0;
              var positionFromTop;
              if (switcher > 2 || switcher < 0) {
                throw [
                      Caml_builtin_exceptions.match_failure,
                      [
                        "Skeleton.re",
                        12,
                        26
                      ]
                    ];
              } else {
                switch (switcher) {
                  case 0 : 
                      positionFromTop = "16%";
                      break;
                  case 1 : 
                      positionFromTop = "44%";
                      break;
                  case 2 : 
                      positionFromTop = "64%";
                      break;
                  
                }
              }
              if (status === /* Dying */2) {
                console.log(deathTime);
                timeString[0] = String((deathTime << 1)) + "px";
              }
              return React.createElement("div", {
                          className: Cn.make(/* :: */[
                                "skeleton",
                                /* :: */[
                                  Cn.ifTrue(status === /* Dying */2, "dying"),
                                  /* [] */0
                                ]
                              ]),
                          style: {
                            top: positionFromTop,
                            transform: "translateX(" + (String(timeString) + ")")
                          }
                        });
            }),
          /* initialState */rowComponent[/* initialState */10],
          /* retainedProps */rowComponent[/* retainedProps */11],
          /* reducer */rowComponent[/* reducer */12],
          /* subscriptions */rowComponent[/* subscriptions */13],
          /* jsElementWrapped */rowComponent[/* jsElementWrapped */14]
        ];
}

export {
  rowComponent ,
  make ,
  
}
/* rowComponent Not a pure module */
